### PR TITLE
App title to collection title

### PR DESCRIPTION
**Pull request by davidamichelson**
Related to https://github.com/srophe/caesarea/issues/78

@wsalesky I edited templates/bibl.html and templates/testimonia.html but not templates/page.html.

Is that right?

### CODE REVIEW

**Review by wsalesky — COMMENTED** [review]
Yes, this looks right.

**Comment by davidamichelson** [comment]
@wsalesky This is fixed on the record pages but not on the browse pages. How do I get the Module Browse pages to use collection title not app title?

**Comment by wsalesky** [comment]
@davidamichelson It looks fixed to me? 
Screen Shot 2020-08-12 at 12 34 49 PM

**Comment by davidamichelson** [comment]
Forgot to refresh the cache, it is fine!

**Pull request merged**
